import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Lottie from 'react-lottie';

import birthday from '../assets/1739-birthday.json';
import birthday2 from '../assets/427-happy-birthday.json';
import birthday3 from '../assets/67220-dog-working-lottie-animation.json';

const defaultOptions = {
  loop: true,
  autoplay: true,
  animationData: birthday2,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
};

const defaultOptions3 = {
  loop: true,
  autoplay: true,
  animationData: birthday3,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Feliz Niver <a href="#">Letisia Coelho!</a>
        </h1>

        <div style={{ width: 300 }}>

          <Lottie options={defaultOptions} />

          <Image src="/letisia.jpeg" alt="Vercel Logo" width={300} height={400} />
          DE Farael para let

          <Lottie options={defaultOptions3} />  Meg passenado kdjfaskosdjokf
        </div>

      </main>
    </div>
  )
}

export default Home
